{% set name = "pickle5" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4aab3fefd665257c16b95ff158c38bedf26595aebcbf11d264e653866579b175

build:
  number: 0
  skip: true  # [py<36]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pickle5
  commands:
    - python -m pickle5.test.test_pickle

about:
  home: https://github.com/pitrou/pickle5-backport
  license: PSF 2
  license_file: LICENSE
  summary: "Experimental backport of the pickle 5 protocol (PEP 574)"

extra:
  recipe-maintainers:
    - jakirkham
    - pitrou
