# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "dxEUZf3BnUonw2ndMwFYOVc8CwN9QsT8bXucOak7yp9W/EZ973Ub8kFex2iwiVET2Psa+W/Hdq4SDDL18REH4qzJMa3goaCuCp5yzpqJ2lz0py4ZoPEFONS9th5Y+TssPKP6t8b7F/DAAafEOM+W84WkDJi6ElH0H/DEt8v8o/SAFDNXogBbEokBzJJABibysTQ4Z3e9Mc/h953kvnXZMB/m4nuMlveUBFJ5inXpJZdudUgFadFB+Q/PBqg7ymUnyZZKh/XLbJjydQIpjmfDGVu40o9ry6ueg7F5VJF8IJLr1gIMpdIxED018BpdgytBRIOD/CvTRA6PEX4Mhutf97ZO/rxLdCeXTxH+mP1nKI5W5jc/SV2CFUHHocVr4Xk7bFyI8oGKoEZAlIeSK0U4YeJgfqUn2yiROLS/RlM6o0TkSvz3G2/iC+biGO8s6Y4SVZZlRBZJH7+Kw7Og6uaMntci0EpqGTVRQfg7dK24J0a7xu7493GFG3xytUC3+7mhXw/Yuw8q2lOUDttE9yv3h1fOKChEutaZWS1C7ta7RawayGzS+cGEqpL961ucHPPcYci6zl34fU2wiDFP7mF+046iTSms64CvEmxY3+e7UClkSmsvvt4gsnSyuLwRLVDVtbNYajZc1DkeKsGXN61reL8/qrzavtVx5OgtjzqC5LU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
