travis:
  secure:
    BINSTAR_TOKEN: dxEUZf3BnUonw2ndMwFYOVc8CwN9QsT8bXucOak7yp9W/EZ973Ub8kFex2iwiVET2Psa+W/Hdq4SDDL18REH4qzJMa3goaCuCp5yzpqJ2lz0py4ZoPEFONS9th5Y+TssPKP6t8b7F/DAAafEOM+W84WkDJi6ElH0H/DEt8v8o/SAFDNXogBbEokBzJJABibysTQ4Z3e9Mc/h953kvnXZMB/m4nuMlveUBFJ5inXpJZdudUgFadFB+Q/PBqg7ymUnyZZKh/XLbJjydQIpjmfDGVu40o9ry6ueg7F5VJF8IJLr1gIMpdIxED018BpdgytBRIOD/CvTRA6PEX4Mhutf97ZO/rxLdCeXTxH+mP1nKI5W5jc/SV2CFUHHocVr4Xk7bFyI8oGKoEZAlIeSK0U4YeJgfqUn2yiROLS/RlM6o0TkSvz3G2/iC+biGO8s6Y4SVZZlRBZJH7+Kw7Og6uaMntci0EpqGTVRQfg7dK24J0a7xu7493GFG3xytUC3+7mhXw/Yuw8q2lOUDttE9yv3h1fOKChEutaZWS1C7ta7RawayGzS+cGEqpL961ucHPPcYci6zl34fU2wiDFP7mF+046iTSms64CvEmxY3+e7UClkSmsvvt4gsnSyuLwRLVDVtbNYajZc1DkeKsGXN61reL8/qrzavtVx5OgtjzqC5LU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
